# -*- coding: utf-8 -*-
"""Files, exceptional handling, logging and memory management.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C9SIT8zlxI-VPx_FP_-k4u7YcmZ_4IzH
"""



"""Files, exceptional handling, logging and memory management - Assignment
1. What is the difference between interpreted and compiled languages?

Answer:
Compiled languages convert code into machine code before execution, while interpreted languages execute code line-by-line at runtime.

2. What is exception handling in Python?

Answer:
Exception handling is a mechanism to manage runtime errors using try, except, else, and finally.

3. What is the purpose of the finally block in exception handling?

Answer:
It executes always, regardless of exceptions, and is used for cleanup like closing files.

4. What is logging in Python?

Answer:
Logging records events, errors, warnings, and information while a program runs.

5. What is the significance of the del method in Python?

Answer:
It acts as a destructor, automatically called when an object is deleted to free resources.

6. What is the difference between import and from ... import in Python?

Answer:
import module imports entire module;
from module import x imports only specific items.

7. How can you handle multiple exceptions in Python?

Answer:
By using multiple except blocks or combining exceptions in a tuple.

8. What is the purpose of the with statement when handling files in Python?

Answer:
It ensures automatic closing of files using a context manager.

9. What is the difference between multithreading and multiprocessing?

Answer:
Multithreading → multiple threads share same memory.
Multiprocessing → multiple processes with separate memory.

10. What are the advantages of using logging in a program?

Answer:
Helps with debugging, tracking events, error reporting, and program monitoring.

11. What is memory management in Python?

Answer:
It includes memory allocation, reference counting, and garbage collection.

12. What are the basic steps involved in exception handling in Python?

Answer:

Code in try block

Handle exceptions in except

Optional else for no-error code

finally for cleanup

13. Why is memory management important in Python?

Answer:
It prevents memory leaks, improves performance, and avoids crashes.

14. What is the role of try and except in exception handling?

Answer:
try detects errors; except handles them.

15. How does Python's garbage collection system work?

Answer:
It uses reference counting and a cyclic garbage collector to free unused memory.

16. What is the purpose of the else block in exception handling?

Answer:
Executes only if no exception occurs in try block.

17. What are the common logging levels in Python?

Answer:
DEBUG, INFO, WARNING, ERROR, CRITICAL.

18. What is the difference between os.fork() and multiprocessing in Python?

Answer:
os.fork() works on Unix only;
multiprocessing is cross-platform & safer.

19. What is the importance of closing a file in Python?

Answer:
Free resources and prevent data corruption.

20. What is the difference between file.read() and file.readline()?

Answer:
read() → reads whole file;
readline() → reads one line.

21. What is the logging module in Python used for?

Answer:
To record events, errors, and debugging information.

22. What is the os module in Python used for in file handling?

Answer:
File operations such as checking existence, renaming, deleting, etc.

23. What are the challenges associated with memory management in Python?

Answer:
High memory usage, circular references, slow garbage collection.

24. How do you raise an exception manually in Python?

Answer:

raise Exception("Error message")

25. Why is it important to use multithreading in certain applications?

Answer:
It improves performance in I/O-bound tasks and enables concurrent execution.


### **Practical Questions**

1. How can you open a file for writing in Python and write a string to it?

Answer:
You can open a file using the "w" (write) mode and write a string using the write() function.

with open("output.txt", "w") as f:
    f.write("Hello World")

2. Write a Python program to read the contents of a file and print each line.

Answer:
Use a for loop to print each line after reading the file.

with open("file.txt", "r") as f:
    for line in f:
        print(line.strip())

3. How would you handle a case where the file doesn't exist while trying to open it for reading?

Answer:
Use a try-except block to catch the FileNotFoundError.

try:
    open("nofile.txt")
except FileNotFoundError:
    print("File not found")

4. Write a Python script that reads from one file and writes its content to another file.

Answer:
By opening one file in read mode and another in write mode.

with open("source.txt", "r") as src, open("target.txt", "w") as dst:
    for line in src:
        dst.write(line)

5. How would you catch and handle division by zero error in Python?

Answer:
Use try-except to catch ZeroDivisionError.

try:
    x = 10 / 0
except ZeroDivisionError:
    print("Cannot divide by zero")

6. Write a Python program that logs an error message to a log file when a division by zero exception occurs.

Answer:
Use the logging module.

import logging
logging.basicConfig(filename="error.log", level=logging.ERROR)

try:
    10 / 0
except ZeroDivisionError:
    logging.error("Division by zero occurred")

7. How do you log information at different levels (INFO, ERROR, WARNING) in Python using the logging module?

Answer:
You can log messages using various levels.

import logging
logging.basicConfig(level=logging.INFO)

logging.info("This is an INFO message")
logging.warning("This is a WARNING message")
logging.error("This is an ERROR message")

8. Write a program to handle a file opening error using exception handling.

Answer:

try:
    open("unknown.txt")
except Exception as e:
    print("Error:", e)

9. How can you read a file line by line and store its content in a list in Python?

Answer:

with open("file.txt", "r") as f:
    lines = f.readlines()

10. How can you append data to an existing file in Python?

Answer:

with open("file.txt", "a") as f:
    f.write("New line added\n")

11. Write a Python program that uses a try-except block to handle an error when attempting to access a dictionary key that doesn't exist.

Answer:

try:
    d = {"a": 1}
    print(d["b"])
except KeyError:
    print("Key not found")

12. Write a program that demonstrates using multiple except blocks to handle different types of exceptions.

Answer:

try:
    x = int("abc")
except ValueError:
    print("Value error")
except TypeError:
    print("Type error")

13. How would you check if a file exists before attempting to read it in Python?

Answer:

import os
print(os.path.exists("file.txt"))

14. Write a program that uses the logging module to log both informational and error messages.

Answer:

import logging
logging.basicConfig(filename="app.log", level=logging.DEBUG)

logging.info("Program started")
logging.error("An error occurred")

15. Write a Python program that prints the content of a file and handles the case when the file is empty.

Answer:

import os

if os.path.getsize("file.txt") == 0:
    print("File is empty")
else:
    with open("file.txt") as f:
        print(f.read())

16. Demonstrate how to use memory profiling to check the memory usage of a small program.

Answer:
You need to install memory_profiler first.

from memory_profiler import profile

@profile
def test():
    a = [i for i in range(10000)]

17. Write a Python program to create and write a list of numbers to a file, one number per line.

Answer:

with open("numbers.txt", "w") as f:
    for i in range(1, 51):
        f.write(str(i) + "\n")

18. How would you implement a basic logging setup that logs to a file with rotation after 1MB?

Answer:

from logging.handlers import RotatingFileHandler
import logging

handler = RotatingFileHandler("rotate.log", maxBytes=1_000_000, backupCount=3)
logger = logging.getLogger("rotator")
logger.setLevel(logging.INFO)
logger.addHandler(handler)

logger.info("Rotating log message")

19. Write a program that handles both IndexError and KeyError using a try-except block.

Answer:

try:
    lst = [1]
    print(lst[5])
    d = {}
    print(d["x"])
except (IndexError, KeyError):
    print("Index or Key error")

20. How would you open a file and read its contents using a context manager in Python?

Answer:

with open("file.txt") as f:
    print(f.read())

21. Write a Python program that reads a file and prints the number of occurrences of a specific word.

Answer:

word = "python"
count = 0

with open("file.txt") as f:
    for line in f:
        count += line.lower().count(word)

print("Occurrences:", count)

22. How can you check if a file is empty before attempting to read its contents?

Answer:

import os
print(os.path.getsize("file.txt") == 0)

23. Write a Python program that writes to a log file when an error occurs during file handling.

Answer:

import logging
logging.basicConfig(filename="file_error.log", level=logging.ERROR)

try:
    open("missing_file.txt")
except Exception as e:
    logging.error(f"Error occurred: {e}")






"""