# -*- coding: utf-8 -*-
"""Restful API & Flask  Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Euaxuk-Nz2UTISO7jMAsRTYswxpeua0m
"""



"""Restful API & Flask | Assignment

Question 1 : What is a RESTful API?
ans->>A RESTful API is an application programming interface that follows the principles of REST (Representational State Transfer). It allows different systems to communicate over the internet using standard HTTP methods like GET, POST, PUT, and DELETE. RESTful APIs use URLs to represent resources and usually return data in JSON format.

Question 2: What is Flask, and why is it popular for building APIs?

Answer:
Flask is a lightweight and flexible Python web framework used to build web applications and APIs. It is popular because it is simple to learn, easy to set up, and provides only the essential tools, allowing developers to add extensions as needed. Its minimal design makes it perfect for creating RESTful APIs quickly.

Question 3: What are HTTP methods used in RESTful APIs?

Answer:
The main HTTP methods used in RESTful APIs are:

GET – Retrieve data from the server

POST – Send new data to the server

PUT – Update existing data

PATCH – Partially update data

DELETE – Remove data
These methods help define how clients interact with API resources.

Question 4: What is the purpose of the @app.route() decorator in Flask?

Answer:
The @app.route() decorator defines the URL path for a specific function in a Flask app. It tells Flask which URL should trigger which function. This helps map web requests to Python functions, making routing easy.

Question 5: What is the role of Flask-SQLAlchemy?

Answer:
Flask-SQLAlchemy is an extension that helps integrate SQLAlchemy with Flask. It simplifies working with databases by allowing developers to create models, run queries, and manage database operations using Python classes instead of writing raw SQL.

Question 6: How do you create a basic Flask application?

Answer:
A basic Flask app is created using the following steps:

Install Flask

Create a Python file (app.py)

Write code:
from flask import Flask
app = Flask(__name__)

@app.route("/")
def home():
    return "Hello, Flask!"

if __name__ == "__main__":
    app.run(debug=True)
Run the file to start the server.

Question 7: How do you return JSON responses in Flask?

Answer:
Flask provides the jsonify() function to return JSON responses. Example:

from flask import jsonify

@app.route("/data")
def data():
    return jsonify({"message": "Hello", "status": "success"})


jsonify() automatically converts Python dictionaries to JSON format.

Question 8: How do you handle POST requests in Flask?

Answer:
POST requests are handled using the methods=["POST"] parameter in the route. Example:

from flask import request

@app.route("/submit", methods=["POST"])
def submit():
    data = request.get_json()
    return {"received": data}, 200


Here, the server reads data sent by the client and returns a confirmation.

Question 9: How do you handle errors in Flask (e.g., 404)?

Answer:
Flask uses error handlers to manage errors like 404 (Not Found). Example:

@app.errorhandler(404)
def page_not_found(e):
    return {"error": "Page not found"}, 404


This returns a custom message instead of the default error page.

Question 10: How do you structure a Flask app using Blueprints?

Answer:
Blueprints help organize a large Flask project into modules. Steps:

Create a Blueprint file (e.g., users.py):

from flask import Blueprint

users_bp = Blueprint("users", __name__)

@users_bp.route("/users")
def get_users():
    return {"users": []}

Register it in the main app:

from flask import Flask
from users import users_bp

app = Flask(__name__)
app.register_blueprint(users_bp)
Blueprints keep code clean, reusable, and easy to maintain.

"""